version: '2'

services:
  postgres:
    image: 'postgres:16.2'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:7.2'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  server:
    build: backend/.
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "api.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - './backend:/backend'
    ports:
      - '8000:8000'

  client:
    build: frontend/.
    command: npm run start
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - './frontend/:/frontend'
      - '/frontend/node_modules'

volumes:
  postgres: null
  redis: null
